$PULP_PATH/rtl/apb_mock_uart.sv
$PULP_PATH/rtl/axi_node_intf_wrap.sv
$PULP_PATH/rtl/axi_slice_wrap.sv
$PULP_PATH/rtl/axi_spi_slave_wrap.sv
$PULP_PATH/rtl/boot_code.sv
$PULP_PATH/rtl/boot_rom_wrap.sv
$PULP_PATH/rtl/clk_rst_gen.sv
$PULP_PATH/rtl/components/cluster_clock_gating.sv
$PULP_PATH/rtl/components/cluster_clock_inverter.sv
$PULP_PATH/rtl/components/cluster_clock_mux2.sv
$PULP_PATH/rtl/components/dp_ram.sv
$PULP_PATH/rtl/components/generic_fifo.sv
$PULP_PATH/rtl/components/pulp_clock_gating.sv
$PULP_PATH/rtl/components/pulp_clock_inverter.sv
$PULP_PATH/rtl/components/pulp_clock_mux2.sv
$PULP_PATH/rtl/components/rstgen.sv
$PULP_PATH/rtl/components/sp_ram.sv
$PULP_PATH/rtl/core2axi_wrap.sv
$PULP_PATH/rtl/core_region.sv
$PULP_PATH/rtl/dp_ram_wrap.sv
$PULP_PATH/rtl/includes/apb_bus.sv
$PULP_PATH/rtl/includes/apu_defines.sv
$PULP_PATH/rtl/includes/axi_bus.sv
$PULP_PATH/rtl/includes/config.sv
$PULP_PATH/rtl/includes/debug_bus.sv
$PULP_PATH/rtl/instr_ram_wrap.sv
$PULP_PATH/rtl/periph_bus_wrap.sv
$PULP_PATH/rtl/peripherals.sv
$PULP_PATH/rtl/pulpino_top.sv
$PULP_PATH/rtl/ram_mux.sv
$PULP_PATH/rtl/random_stalls.sv
$PULP_PATH/rtl/sp_ram_wrap.sv
$PULP_PATH/rtl/axi2apb_wrap.sv
$PULP_PATH/rtl/axi_mem_if_SP_wrap.sv
